In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,np.nan],[13,14,15],[16,17,18],[19,20,21]], columns=["A", "B", "C"], index=["x","y","z",'zz',"D","e","f"])
print(df)

     A   B     C
x    1   2   3.0
y    4   5   6.0
z    7   8   9.0
zz  10  11   NaN
D   13  14  15.0
e   16  17  18.0
f   19  20  21.0

In [65]:
df.head()

     A   B     C
x    1   2   3.0
y    4   5   6.0
z    7   8   9.0
zz  10  11   NaN
D   13  14  15.0

In [66]:
df.tail() #print last 5 rows

     A   B     C
z    7   8   9.0
zz  10  11   NaN
D   13  14  15.0
e   16  17  18.0
f   19  20  21.0

In [67]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [68]:
df.index.tolist()

['x', 'y', 'z', 'zz', 'D', 'e', 'f']

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, x to f
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       7 non-null      int64
 1   B       7 non-null      int64
 2   C       6 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 224.0+ bytes

In [70]:
df.describe()

               A          B          C
count   7.000000   7.000000   6.000000
mean   10.000000  11.000000  12.000000
std     6.480741   6.480741   7.099296
min     1.000000   2.000000   3.000000
25%     5.500000   6.500000   6.750000
50%    10.000000  11.000000  12.000000
75%    14.500000  15.500000  17.250000
max    19.000000  20.000000  21.000000

In [71]:

df.nunique()

A    7
B    7
C    6
dtype: int64

In [72]:
df['A'].unique()

array([ 1,  4,  7, 10, 13, 16, 19])

In [73]:
df.shape

(7, 3)

In [74]:
df.size

21

In [76]:
df

     A   B     C
x    1   2   3.0
y    4   5   6.0
z    7   8   9.0
zz  10  11   NaN
D   13  14  15.0
e   16  17  18.0
f   19  20  21.0