In [ ]:
import numpy as np
import pandas as pd

In [52]:
df = pd.read_csv("airpassengers.csv")

In [53]:
df

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [54]:
display(df)

       Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [55]:
df.Month

0      1949-01
1      1949-02
2      1949-03
3      1949-04
4      1949-05
        ...
139    1960-08
140    1960-09
141    1960-10
142    1960-11
143    1960-12
Name: Month, Length: 144, dtype: object

In [56]:
df.Month.head(4)

0    1949-01
1    1949-02
2    1949-03
3    1949-04
Name: Month, dtype: object

In [ ]:
df.Passengers

0      112
1      118
2      132
3      129
4      121
      ...
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64

In [62]:
df.loc[:,[0,1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [columns]"